import type { RailEvent } from "@zawa/domain/events";

export interface Env {
  APP_ENV: string;
  RDM_REALTIME_PRODUCT_CODE: string;
  RDM_LDB_PRODUCT_CODE: string;
  RDM_SERVICE_DETAILS_PRODUCT_CODE: string;
  RDM_QUERY_SERVICES_PRODUCT_CODE: string;
  RDM_REFERENCE_DATA_PRODUCT_CODE: string;
  RDM_STATIONS_PRODUCT_CODE: string;
  RDM_STATIONS_JSON_PRODUCT_CODE: string;
  RDM_DISRUPTIONS_PRODUCT_CODE: string;
  RDM_NSI_PRODUCT_CODE: string;
  RDM_INCIDENTS_PRODUCT_CODE: string;
  RDM_TIMETABLE_PRODUCT_CODE: string;
  RDM_TRAIN_MOVEMENTS_PRODUCT_CODE: string;
  RDM_LDB_ARR_DEP_WITH_DETAILS_URL: string;
  RDM_LDB_ARR_DEP_URL: string;
  RDM_SERVICE_DETAILS_URL: string;
  RDM_QUERY_SERVICES_URL: string;
  RDM_QUERY_SERVICE_DETAILS_BY_RID_URL: string;
  RDM_REFERENCE_STATION_LIST_URL: string;
  RDM_REFERENCE_TOC_LIST_URL: string;
  RDM_REFERENCE_REASON_CODE_LIST_URL: string;
  RDM_REFERENCE_LOADING_CATEGORY_URL: string;
  RDM_REFERENCE_SOURCE_INSTANCE_NAMES_URL: string;
  RDM_STATIONS_TOC_URL: string;
  RDM_STATION_BY_CRS_URL: string;
  RDM_DISRUPTION_LIST_URL: string;
  RDM_NSI_URL: string;
  RDM_NSI_TOC_URL: string;
  RDM_INCIDENTS_URL: string;
  INGEST_HEARTBEAT_SECONDS: string;

  RDM_LDB_API_KEY: string;
  RDM_SERVICE_DETAILS_API_KEY: string;
  RDM_QUERY_SERVICES_API_KEY: string;
  RDM_REFERENCE_DATA_API_KEY: string;
  RDM_STATIONS_API_KEY: string;
  RDM_DISRUPTIONS_API_KEY: string;
  RDM_NSI_API_KEY: string;
  RDM_INCIDENTS_API_KEY: string;

  DB: D1Database;
  RAIL_EVENTS_QUEUE: Queue<RailEvent>;

  STATION_BOARD_DO: DurableObjectNamespace;
  SERVICE_DO: DurableObjectNamespace;

  ASSETS: Fetcher;
}
